[package]
name = "riscv-shared"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Shared code for RISC-V JIT testing"

[lib]

[dependencies]
lpc-lpir = { path = "../lpc-lpir" }
lpc-codegen = { path = "../lpc-codegen" }



