[package]
name = "riscv32-encoder"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "RISC-V 32-bit instruction encoder"

[lib]

[dependencies]
nom = { version = "7", default-features = false, features = ["alloc"] }

[dev-dependencies]
