# Use nightly rustfmt features
edition = "2021"
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
imports_granularity = "Crate"
imports_layout = "Mixed"
group_imports = "StdExternalCrate"
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true




