[package]
name = "r5-builder"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "IR builder for constructing RISC-V 5 IR"

[lib]

[dependencies]
r5-ir = { path = "../r5-ir" }

[dev-dependencies]

