[package]
name = "lpc-lpir"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "RISC-V 5 Intermediate Representation"

[lib]

[dependencies]
nom = { version = "7", default-features = false, features = ["alloc"] }

[dev-dependencies]

