[package]
name = "lpc-filetests"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
lpc-codegen = { path = "../lpc-codegen" }
lpc-lpir = { path = "../lpc-lpir" }
filecheck = "0.4"

